apiVersion : apps/v1
kind: Deployment
metadata:
  name: book 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book 
  template:
    metadata:
      labels:
        app: book 
    spec:
      containers:
        - name: book 
          image: ${ACR_NAME}.azurecr.io/book
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: book
